export const CHANGE_WIDTH_SIZE = "CHANGE_WIDTH_SIZE";
export const CHANGE_HEIGHT_SIZE = 'CHANGE_HEIGHT_SIZE';
export const CHANGE_PROBABILITY = 'CHANGE_PROBABILITY';
export const CLICK_CREATE_BTN = 'CLICK_CREATE_BTN';