export const CHANGE_WIDTH_SIZE = "CHANGE_WIDTH_SIZE";
export const CHANGE_HEIGHT_SIZE = 'CHANGE_HEIGHT_SIZE';
export const CHANGE_PROBABILITY = 'CHANGE_PROBABILITY';
export const CLICK_CREATE_BTN = 'CLICK_CREATE_BTN';
export const MOVE_UP_CHARACTER = 'MOVE_UP_CHARACTER';
export const MOVE_DOWN_CHARACTER = 'MOVE_DOWN_CHARACTER';
export const MOVE_RIGHT_CHARACTER = 'MOVE_RIGHT_CHARACTER';
export const MOVE_LEFT_CHARACTER = 'MOVE_LEFT_CHARACTER';